GET https://api.brawlstars.com/v1
Authorization: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiIsImtpZCI6IjI4YTMxOGY3LTAwMDAtYTFlYi03ZmExLTJjNzQzM2M2Y2NhNSJ9.eyJpc3MiOiJzdXBlcmNlbGwiLCJhdWQiOiJzdXBlcmNlbGw6Z2FtZWFwaSIsImp0aSI6IjAyZTQ5NmNlLWVmN2ItNDAxNS04YzA5LWRkNjE2ZGZlOTRhZCIsImlhdCI6MTcxNDQ5NzQxNiwic3ViIjoiZGV2ZWxvcGVyLzE3YjU4YzljLTcxOTktMTk5ZS1lZWU0LTAwOGMwNWI3NzE5OSIsInNjb3BlcyI6WyJicmF3bHN0YXJzIl0sImxpbWl0cyI6W3sidGllciI6ImRldmVsb3Blci9zaWx2ZXIiLCJ0eXBlIjoidGhyb3R0bGluZyJ9LHsiY2lkcnMiOlsiMjAxLjIzNS4xMjEuNzYiXSwidHlwZSI6ImNsaWVudCJ9XX0.Iof_rMTh1b8ev1LLhS3MCZB7MKakwQPpWUntPnDLXhF1AFjpHBEUYNV4PiFHb0kKIdxTI9tnzGtezDw36zk87Q
